In [2]:
a = [1,2,3,4,5,7]

In [3]:
a

[1, 2, 3, 4, 5, 7]

In [4]:
c = 2 * a
c

[1, 2, 3, 4, 5, 7, 1, 2, 3, 4, 5, 7]

Duplicó el array a

In [5]:
d = [3,5,6,9,7,8]

In [6]:
e = a + d
e

[1, 2, 3, 4, 5, 7, 3, 5, 6, 9, 7, 8]

Concatenó los dos arrays

Los métodos anteriores son de listas de python, sin usar numpy.

Se puede ver que su comportamiento no fue exactamente el deseado.

Numpy maneja mejor estas operaciones de vectores.

## Funciones de numpy

In [7]:
import numpy as np

In [8]:
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])

c = a + b

print(c)
print(type(c))
print(c.shape)

[ 4  8 11 14 18]
<class 'numpy.ndarray'>
(5,)


Ahora sí hace una suma correcta de vectores

In [9]:
l = [[1,2,3],[3,6,9],[2,4,6]] # Crear una lista de listas
a = np.array(l) # Convierte la lista a un array de numpy
print(a)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [3 6 9]
 [2 4 6]]
(3, 3)
int64


También se pueden importar directamente como una matriz

In [10]:
M = np.array([[1,2],[3,4]])
print(M.shape)
print(M.dtype)

(2, 2)
int64


Uso de matrices

In [11]:
print(a)
print(a[0]) # Obtengo solo el primer elemento de la matriz.
print(a[1,2]) # De la segunda fila, el tercer elemento
print(a[1,1:3]) # De la segunda fila, del segundo al tercer elemento
print(a[:,1]) # obtener segunda columna
# También se pueden sobreescribir los elementos que ya están en la matriz
print(a[1,2]) # Aquí es 9
a[1,2] = 7
print(a[1,2]) # Ahora es 7
print(a)
# También puedo modificar una columna
a[:,0] = [0,9,8]
print(a)


[[1 2 3]
 [3 6 9]
 [2 4 6]]
[1 2 3]
9
[6 9]
[2 6 4]
9
7
[[1 2 3]
 [3 6 7]
 [2 4 6]]
[[0 2 3]
 [9 6 7]
 [8 4 6]]


Funcionas generadoras en numpy

In [12]:
x = np.arange(0,10,1)
print(x) # Se hizo un array del 0 al 9
print(np.linspace(0,10,25)) # Hacer 25 números con saltos iguales, del 0 al 10
print(np.logspace(0,10,10, base=np.e)) # Hacer números separados con escala logarítmica.


[0 1 2 3 4 5 6 7 8 9]
[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]
[1.00000000e+00 3.03773178e+00 9.22781435e+00 2.80316249e+01
 8.51525577e+01 2.58670631e+02 7.85771994e+02 2.38696456e+03
 7.25095809e+03 2.20264658e+04]


In [13]:
print(np.diag([1,2,3])) # Hacer matriz diagonal con 1,2,3 en su diagonal.
b = np.zeros(5) # Hacer arreglo con 5 ceros.
print(b)
print(b.dtype)
n = 1000
my_int_array = np.zeros(n, dtype=int) # Hacer array de 1000 ceros, en forma entera
print(my_int_array.dtype)

c = np.ones((3,3)) # Hacer matriz de 3x3, con solamente unos.
print(c)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0. 0. 0. 0. 0.]
float64
int64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
d = np.arange(5)
print(d)

d[1] = 9.7 # Intento asignar un flotante al array
print(d) # Pero el tipo entero se mantiene

print(d*0.4) # En operaciones, sí se cambia el tipo, pero es en un nuevo array.

d = np.arange(5, dtype=float) # Así puedo hacer el array con flotantes
print(d)

np.arange(3,7,0.5) # Hacer array del 3 al 7, con saltos de 0.5

[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]
[0. 1. 2. 3. 4.]


array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5])

In [15]:
x,y = np.mgrid[0:5, 0:5]
# Hace dos matrices 5x5.
# La primera con filas con todos 0, todos 1,,,,
print(x)
# Y la segunda con columnas todos 0, todos 1...
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [16]:
import os
os.system("head DeBilt.txt")
# Leer archivo
data = np.genfromtxt("DeBilt.txt")
data.shape

# Esto guarda el dataset en un archivo
np.savetxt('datasaved.txt', data)

In [19]:
M = np.random.rand(3,3) # Crear matriz 3x3 con valores random
print(M)

np.save('saved-matriz.npy', M) # Guardar matriz en archivo
np.load('saved-matriz.npy') # Cargar archivo npy

[[0.2775558  0.52859779 0.69912727]
 [0.4989252  0.51239227 0.0917937 ]
 [0.07647654 0.76731232 0.58604157]]


array([[0.2775558 , 0.52859779, 0.69912727],
       [0.4989252 , 0.51239227, 0.0917937 ],
       [0.07647654, 0.76731232, 0.58604157]])

In [33]:
a = np.arange(4.0) # Array del 0 al 3
print(a)
b = a * 23.4 # Multiplicación por escalar
print(b)
c = b / (a+1)
print(c) # División por escalar, primero se hizo una suma + 1 a todo a
c += 10
print(c) # Sumarle 10 a todos los elementos de c

arr = np.arange(100,200) # Array de 100 elementos del 100 al 199
select = [5,25,50,75,-5]
print(arr[select]) # Mostrar los elementos en los indices 5,25,...,-5 de arr

# Primero hace un array con 10 elementos del 10 al 19, luego lo convierte
# a una matriz de 2x5
arr = np.arange(10,20).reshape((2,5))
print(arr)

[0. 1. 2. 3.]
[ 0.  23.4 46.8 70.2]
[ 0.   11.7  15.6  17.55]
[10.   21.7  25.6  27.55]
[105 125 150 175 195]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [37]:
print(arr.sum()) # Suma todos los elementos de la matriz
print(arr.mean()) # Promedio de todos los elementos en la matriz
print(arr.std()) # Desviación estandar de la matriz
print(arr.max()) # Máximo de la matriz
print(arr.min()) # Mínimo de la matriz

145
14.5
2.8722813232690143
19
10


In [42]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort() # Ordenar array
print(arr)

x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)
print(x)

# .sort() modifica el array, np.sort() no


[1.2 1.8 2.3 4.5 5.5 6.7]
[4.5 2.3 6.7 1.2 1.8 5.5]


In [50]:
a = np.array([[1.0, 2.0], [4.0,3.0]])
print(a)
print(a.transpose()) # Transpuesta de matriz
# print(np.inv(a)) # Inversa de matriz
u = np.eye(2)
print(u)

j = np.array([[0.0,-1.0],[1.0,0.0]])
np.dot(j,j)


[[1. 2.]
 [4. 3.]]
[[1. 4.]
 [2. 3.]]
[[1. 0.]
 [0. 1.]]


array([[-1.,  0.],
       [ 0., -1.]])

In [62]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a+b) # Suma vectores
print(a-b) # resta
print(a*b) # multiplicación
print(b/a) # división
print(a%b) # modulo
print(a**b) # potencia

a = np.array([[1,2], [3,4], [5,6]], float)
b = np.array([-1,3], float)
print(a)
print(b)

print(a+b) # Suma de matriz + vector

print(a * a) # Multiplicación matrices
 
print(b*b) # Multiplicación vectores

print(a*b) # matriz por vector


[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  1.   4. 729.]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[-1.  3.]
[[0. 5.]
 [2. 7.]
 [4. 9.]]
[[ 1.  4.]
 [ 9. 16.]
 [25. 36.]]
[1. 9.]
[[-1.  6.]
 [-3. 12.]
 [-5. 18.]]
